# Copyright 2025 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# ==============================================================================

"""Visualize logs and store results from unlearning experiments.

This script processes experiment logs generated by the corrective unlearning
benchmarking framework (based on
https://github.com/drimpossible/corrective-unlearning-bench). It parses
directory names to extract pretraining and unlearning arguments, computes
accuracies from prediction files, and stores the results in CSV and TSV formats.
"""

import os
import numpy as np
import pandas as pd
from utils import get_targeted_classes


def parse_pretrain_dirname(dirname, preargnamelist):
  arglist = dirname.split("_")
  print(arglist)
  print(preargnamelist)
  assert len(arglist) == len(preargnamelist)
  pretrain_args = {}
  for idx, name in enumerate(preargnamelist):
    pretrain_args[name] = arglist[idx]
  return pretrain_args


def parse_unlearn_dirname(dirname, unargnamelist, args):
  """Parses the unlearning directory name to extract unlearning arguments.

  The directory name is expected to be structured with underscores separating
  different argument values. The parsing logic depends on the specific
  unlearning method identified in the dirname.

  Args:
    dirname: The name of the unlearning directory.
    unargnamelist: A list of expected argument names for unlearning.
    args: Additional arguments, potentially containing `p_cut`.

  Returns:
    A dictionary containing the parsed unlearning arguments.
  """
  arglist = dirname.split("_")
  assert len(arglist) >= 2
  un_args = dict((arg, "") for arg in unargnamelist)
  if arglist[0] == "Naive":
    un_args["unlearn_method"], un_args["exp_name"] = arglist[0], arglist[1]
    un_args["deletion_size"] = 0
    return un_args
  un_args["deletion_size"], un_args["unlearn_method"], un_args["exp_name"] = (
      arglist[0],
      arglist[1],
      arglist[2],
  )
  print("===> arglist: ", arglist)
  if arglist[1] in [
      "EU",
      "CF",
      "Mixed",
      "Scrub",
      "BadT",
      "SSD",
      "AscentLearn",
      "ScrubNew",
      "ALnew",
      "ASSD",
      "ASSDR",
      "ALFSSD",
      "XALFSSD",
      "RAYN",
      "No_unlearning",
  ]:
    assert len(arglist) >= 5
    un_args["train_iters"], un_args["k"] = arglist[3], arglist[4]
  if arglist[1] in ["Mixed"]:
    assert len(arglist) >= 6
    un_args["factor"] = arglist[5]
  if arglist[1] in ["AscentLearn", "ALnew"]:
    assert len(arglist) >= 6
    un_args["ascLRscale"] = arglist[5]
  if arglist[1] == "InfRe":
    assert len(arglist) >= 8
    un_args["msteps"], un_args["rsteps"], un_args["ascLRscale"] = (
        arglist[5],
        arglist[6],
        arglist[7],
    )
  if arglist[1] == "Scrub":
    assert len(arglist) >= 8
    un_args["kd_T"], un_args["alpha"], un_args["msteps"] = arglist[5:8]
  if arglist[1] == "ScrubNew":
    assert len(arglist) >= 8
    un_args["kd_T"], un_args["alpha"], un_args["ascLRscale"] = arglist[5:8]
  if arglist[1] == "SSD":
    assert len(arglist) >= 7
    un_args["SSDdampening"], un_args["selectwt"] = arglist[5], arglist[6]
  if arglist[1] == "ASSD":
    assert len(arglist) >= 5
    un_args["frac"] = args.p_cut
  if arglist[1] == "ALFSSD":
    assert len(arglist) >= 5
    print("ARGLIST", arglist)
    un_args["frac"] = args.p_cut
  if arglist[1] == "XALFSSD":
    assert len(arglist) >= 5
    un_args["frac"] = args.p_cut
  return un_args


def compute_accuracy(preds, y):
  return np.equal(np.argmax(preds, axis=1), y).mean()


def parse_unpath(un_path, pre_args, un_args, args, headers, writer):
  """Parses unlearning results from a given path and computes metrics.

  This function loads prediction and target files from the specified unlearning
  path, computes various accuracy metrics based on the dataset method, and
  updates a dictionary with these results. It also logs some metrics using the
  provided writer.

  Args:
    un_path: The file system path to the unlearning experiment results.
    pre_args: Dictionary containing pretraining arguments.
    un_args: Dictionary containing unlearning arguments.
    args: Additional arguments, likely from command-line parsing.
    headers: A list of header names for the result dictionary.
    writer: An object with an `add_scalar` method for logging.

  Returns:
    A dictionary containing combined pretraining, unlearning arguments, and
    computed metrics.
  """
  ret = dict((key, "") for key in headers)
  ret.update(pre_args)
  ret.update(un_args)
  # load training time here and then add to rest
  tr_preds = np.load(un_path + "/preds_train.npy")
  tr_y = np.load(un_path + "/targetstrain.npy")
  te_preds = np.load(un_path + "/preds_test.npy")
  te_y = np.load(un_path + "/targetstest.npy")
  un_time = np.load(un_path + "/unlearn_time.npy")
  ret["unlearn_time"] = un_time
  forget_idx = np.load(
      args.dirpath
      + "/"
      + pre_args["dataset"]
      + "_"
      + pre_args["dataset_method"]
      + "_"
      + pre_args["forget_set_size"]
      + "_manip.npy"
  )
  delete_idx = None
  if un_args["deletion_size"] != 0:
    delete_idx = np.load(
        args.dirpath
        + "/"
        + pre_args["dataset"]
        + "_"
        + pre_args["dataset_method"]
        + "_"
        + pre_args["forget_set_size"]
        + "_"
        + un_args["deletion_size"]
        + "_deletion.npy"
    )
  ret["train_clean_acc"] = compute_accuracy(tr_preds, tr_y)
  delete_acc, delete_err = 0.0, 101.0
  if pre_args["dataset_method"] == "poisoning":
    tr_adv_preds = np.load(un_path + "/preds_adv_train.npy")
    tr_adv_y = np.load(un_path + "/targetsadv_train.npy")
    tr_wrong = np.zeros(tr_adv_y.shape)
    te_adv_preds = np.load(un_path + "/preds_adv_test.npy")
    te_adv_y = np.load(un_path + "/targetsadv_test.npy")
    forget_acc = compute_accuracy(
        tr_adv_preds[forget_idx], tr_adv_y[forget_idx]
    )
    if un_args["deletion_size"] != 0:
      print("delete_idx", delete_idx)
      delete_err = compute_accuracy(
          tr_adv_preds[delete_idx],
          tr_wrong[delete_idx],  # removed brackets here to fix the error
      )
      delete_acc = compute_accuracy(
          tr_adv_preds[delete_idx], tr_adv_y[delete_idx]
      )
    test_acc = compute_accuracy(te_adv_preds, te_adv_y)
    forget_clean_acc = compute_accuracy(tr_preds[forget_idx], tr_y[forget_idx])
    test_clean_acc = compute_accuracy(te_preds, te_y)
    print(
        forget_acc, test_acc, forget_clean_acc, test_clean_acc
    )  # REFERENCE: what is what for the paper plots
    (
        ret["delete_acc"],
        ret["delete_err"],
        ret["manip_acc"],
        ret["test_acc"],
        ret["manip_clean_acc"],
        ret["test_clean_acc"],
    ) = (
        delete_acc,
        delete_err,
        forget_acc,
        test_acc,
        forget_clean_acc,
        test_clean_acc,
    )
    writer.add_scalar("Poison/Train_healed", forget_acc, 0)
    writer.add_scalar("Poison/Train_nomanip", forget_clean_acc, 0)
    writer.add_scalar("Poison/Train_healed_onlyidentified", delete_acc, 0)
    writer.add_scalar("Poison/Test_manip", test_acc, 0)
    writer.add_scalar("Poison/Test_nomanip", test_clean_acc, 0)
  if pre_args["dataset_method"] == "randomlabelswap":  # "labelrandom":
    forget_acc = compute_accuracy(tr_preds[forget_idx], tr_y[forget_idx])
    test_acc = compute_accuracy(te_preds, te_y)
    print(forget_acc, test_acc)
    ret["forget_acc"], ret["test_acc"] = forget_acc, test_acc
    writer.add_scalar("RandomLabel/Train_healed", forget_acc, 0)
    writer.add_scalar("RandomLabel/Test_clean", test_acc, 0)
  if pre_args["dataset_method"] == "labeltargeted":
    classes = get_targeted_classes(pre_args["dataset"])
    te_class_idxes = np.concatenate(
        (np.nonzero(te_y == classes[0]), np.nonzero(te_y == classes[1])), axis=1
    ).squeeze()
    retain_idxes = np.setdiff1d(np.arange(len(te_y)), te_class_idxes)
    forget_acc = compute_accuracy(tr_preds[forget_idx], tr_y[forget_idx])
    tr_wrong = tr_y
    tr_wrong[tr_y == classes[0]] = classes[1]
    tr_wrong[tr_y == classes[1]] = classes[0]
    if un_args["deletion_size"] != 0:
      delete_acc = compute_accuracy(tr_preds[delete_idx], tr_y[delete_idx])
      delete_err = compute_accuracy(tr_preds[delete_idx], tr_wrong[delete_idx])
    test_acc = compute_accuracy(te_preds[te_class_idxes], te_y[te_class_idxes])
    test_retain_acc = compute_accuracy(
        te_preds[retain_idxes], te_y[retain_idxes]
    )
    print(forget_acc, test_acc, test_retain_acc)
    (
        ret["delete_acc"],
        ret["delete_err"],
        ret["manip_acc"],
        ret["test_acc"],
        ret["test_retain_acc"],
    ) = (delete_acc, delete_err, forget_acc, test_acc, test_retain_acc)
  if pre_args["dataset_method"] == "interclasslabelswap":
    classes = get_targeted_classes(pre_args["dataset"])
    te_class_idxes = np.concatenate(
        (np.nonzero(te_y == classes[0]), np.nonzero(te_y == classes[1])), axis=1
    ).squeeze()
    retain_idxes = np.setdiff1d(np.arange(len(te_y)), te_class_idxes)
    forget_acc = compute_accuracy(tr_preds[forget_idx], tr_y[forget_idx])
    tr_wrong = tr_y
    tr_wrong[tr_y == classes[0]] = classes[1]
    tr_wrong[tr_y == classes[1]] = classes[0]
    if un_args["deletion_size"] != 0:
      delete_acc = compute_accuracy(tr_preds[delete_idx], tr_y[delete_idx])
      delete_err = compute_accuracy(tr_preds[delete_idx], tr_wrong[delete_idx])
    test_acc = compute_accuracy(te_preds[te_class_idxes], te_y[te_class_idxes])
    test_retain_acc = compute_accuracy(
        te_preds[retain_idxes], te_y[retain_idxes]
    )
    test_acc_all = compute_accuracy(te_preds, te_y)
    print(forget_acc, test_acc, test_retain_acc)
    (
        ret["delete_acc"],
        ret["delete_err"],
        ret["manip_acc"],
        ret["test_acc"],
        ret["test_retain_acc"],
    ) = (delete_acc, delete_err, forget_acc, test_acc, test_retain_acc)
    writer.add_scalar("IC/Train_healed", forget_acc, 0)
    writer.add_scalar("IC/Train_healed_onlyidentified", delete_acc, 0)
    writer.add_scalar("IC/Test_twoclasses_clean", test_acc, 0)
    writer.add_scalar("IC/Test_otherclasses_clean", test_retain_acc, 0)
    writer.add_scalar("IC/Test_all_clean", test_acc_all, 0)
  return ret


def store_results(writer, args):
  """Processes experiment logs, computes metrics, and stores results.

  This function walks through experiment directories, parses pretraining and
  unlearning arguments from directory names, computes accuracy metrics using
  `parse_unpath`, and compiles all results into a Pandas DataFrame. The
  DataFrame is then saved to TSV and CSV files. It also handles logging of some
  metrics via the provided writer.

  Args:
    writer: An object with an `add_scalar` method for logging.
    args: An object containing command-line arguments, including `dirpath`,
      `tsvpath`, and potentially `p_cut`.
  """
  preargnamelist = [
      "train_type",  # new
      "dataset",
      "model",
      "dataset_method",
      "forget_set_size",
      "patch_size",
      "pretrain_iters",
      "pretrain_lr",
      "frac",
  ]
  unargnamelist = [
      "unlearn_method",
      "exp_name",
      "train_iters",
      "k",
      "factor",
      "kd_T",
      "gamma",
      "alpha",
      "msteps",
      "seed",
  ]
  metricslist = [
      "delete_acc",
      "delete_err",
      "manip_acc",
      "test_acc",
      "manip_clean_acc",
      "test_clean_acc",
      "test_retain_acc",
      # "train_time", # new
  ]
  headers = preargnamelist + unargnamelist + metricslist
  rows = []
  for dirname in next(os.walk(args.dirpath))[1]:
    print("--->", dirname)
    print("--->", preargnamelist)
    pre_args = parse_pretrain_dirname(dirname, preargnamelist)
    pretrain_path = os.path.join(args.dirpath, dirname)
    for undirname in next(os.walk(pretrain_path))[1]:
      print(dirname, undirname)
      un_args = parse_unlearn_dirname(undirname, unargnamelist, args)
      un_path = os.path.join(pretrain_path, undirname)
      row = parse_unpath(un_path, pre_args, un_args, args, headers, writer)
      # add run parameters to row
      # iterate over all text files in the un_path and them to the row (dict)
      # with file name (without .txt) as key and the content as the value
      for filename in os.listdir(un_path):
        if filename.endswith(".txt"):
          with open(os.path.join(un_path, filename), "r") as f:
            row[filename[:-4]] = f.read()
      rows.append(row)
  df = pd.DataFrame.from_records(rows)
  # replace all NaN with -0.1 for easy spotting afterwards
  df = df.fillna(-0.1)
  # make deletion_size numbers as int
  df["deletion_size"] = df["deletion_size"].astype(int)
  df["frac"] = df["frac"].astype(float)
  df.to_csv(args.tsvpath, sep="\t")
  # reading given tsv file
  csv_table = pd.read_table("results.tsv", sep="\t")
  csv_table.to_csv("results_iter.csv", index=False, sep=",")
  if os.path.exists("results.csv"):
    pass
  else:
    csv_table.to_csv("results.csv", index=False, sep=",")
  # csv_table.to_csv('results.csv', mode='a', index=False, header=False)
  df1 = pd.read_csv("results.csv", sep=",")
  df2 = pd.read_csv("results_iter.csv", sep=",")
  combined_df = pd.concat([df1, df2])
  combined_df = combined_df.drop_duplicates()
  combined_df.to_csv("results.csv", index=False, sep=",")
  # converting tsv file into csv
  # csv_table.to_csv('results.csv',index=False)
  # my_table = wandb.Table(dataframe=df)
  # wandb.log({"my_table": my_table})
  # wandb.finish()
